### ISSUE TITLE
Does not work on Firefox

### ISSUE THREAD

**Issue by makalu79** [owncloud/impersonate#10]
Uses IE specific Event.srcElement in impersonate.js. When I change line 24 to:
`                        var userid = $(e.target).parents('tr').find('.name').text();`
the app works on firefox. Event.target should work on all newer browsers (see https://developer.mozilla.org/en-US/docs/Web/API/Event/target)

**Comment by m4lvin** [comment]
This is closed with https://github.com/owncloud/impersonate/pull/9

**Comment by butonic** [comment]
yes, awesome!
