### ISSUE TITLE
Cannot Impersonate a user after he has changed its password

### ISSUE THREAD

**Issue by davitol** [owncloud/impersonate#102]
### Steps to reproduce

You can configure it like the screenshots below this ticket

1 - As admin user enable impersonate app
2 - As admin user create a subadmin for a group (ana) and another user that belongs to the group (luis)
3 - Log in as subadmin (ana) (regular way) and also as the user (luis)
4 - Log in again as admin user, change the password of the user that belongs to the group (luis)
5 - Impersonate subadmin (ana) and then try to impersonate the user (luis)

### Expected behaviour

The user can be impersonated

### Actual behaviour

The user is not longer possible to impersonate, even when he logs in again with his new credentials

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.1.15

**ownCloud version:**

ownCloud Stable10 from 5th April  2018 and impersonate 0.1.2

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
No

**Logs**

```
No logs in owncloud.log
```

*Admin account users page*

![screen shot 2018-04-05 at 17 27 06](https://user-images.githubusercontent.com/10596560/38375508-b4b24184-38f6-11e8-929d-2fc56a4ec187.png)

*Subgroup admin (ana) users page*

![screen shot 2018-04-05 at 17 26 52](https://user-images.githubusercontent.com/10596560/38375611-ebdb40d4-38f6-11e8-97d8-a813b625af17.png)

*Settings in User Authentication section in Admin account**

![screen shot 2018-04-05 at 17 27 23](https://user-images.githubusercontent.com/10596560/38375702-1de06848-38f7-11e8-8629-7afb5dcb9539.png)

**Comment by davitol** [comment]
After talking with @sharidas:

```
only one level impersonation is allowed, admin can impersonate any user but once impersonated no further impersonation...
```

So it is not a bug. Closed.

**Comment by andyg2** [comment]
The user needs to log in before impersonation works.
