### ISSUE TITLE
Columns are shifted in the Users Page, when we a guest user is a subadmin and impersonate app is enable

### ISSUE THREAD

**Issue by davitol** [owncloud/impersonate#103]
### Steps to reproduce

You can configure it like the screenshots below this ticket

1 - As admin user enable Impersonate app and Guests app
2 - Create a guest user and grant him as subadmin of a group
3 - Log in as guest user that is a subadmin
4 - Browse to the Users page

### Expected behaviour

The columns should fit with the content

### Actual behaviour

The columns content are shifted (see screenshot below)

![screen shot 2018-04-06 at 09 33 37](https://user-images.githubusercontent.com/10596560/38408704-f61576ae-397e-11e8-835c-453c2629609c.png)

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.1.15

**ownCloud version:**

ownCloud Stable10 from 5th April  2018 and impersonate 0.1.3 and guests app

**Updated from an older ownCloud or fresh install:**
Fresh

**Are you using external storage, if yes which one:** 
No

**Are you using encryption:** 
No

**Logs**

```
No logs in owncloud.log
```

**Comment by sharidas** [comment]
When guests app is not used, this issue is not reproducible. Will investigate on what is causing the issue with guests app.

**Comment by PVince81** [comment]
will be solved once we have the default whitelist: https://github.com/owncloud/guests/issues/171
