### ISSUE TITLE
Unable to run impersonate

### ISSUE THREAD

**Issue by paurakhsharma** [owncloud/impersonate#108]
I am on ownCloud `stable10`  and installed `impersonate` through git.

Now on my user's page, I have an infinitely going loading icon 
and some javascript errors.
What might be the reasons for this?
![image](https://user-images.githubusercontent.com/20378877/39358840-54433fa4-4a37-11e8-9793-63e4d87239b4.png)

**Comment by sharidas** [comment]
@paurakhsharma May I know the steps followed for for installing impersonate, please?

**Comment by paurakhsharma** [comment]
Oh yeah thanks, I forgot that step.
It's working fine now
