### ISSUE TITLE
Django-impersonate 0.9.1

### ISSUE THREAD

**Issue by vineet4may** [owncloud/impersonate#11]
Hello all,
In my project, I used **Django-impersonate 0.9.1** package with Python version **python 2.7** and Django version **Django 1.8.5**.
But when I run my project in my local system, it works fine. But if I run same online (with nginx gunicorn) its (impersonate) not work. What should I do?
Help me!

**Comment by DeepDiver1975** [comment]
django? This is owncloud!

I assume you did choose the wrong repo.
