### ISSUE TITLE
[FR] Option to always allow subadmins to impersonate their group members

### ISSUE THREAD

**Issue by tomneedham** [owncloud/impersonate#132]

**Comment by tomneedham** [comment]
@pmaier1

**Comment by pmaier1** [comment]
Currently you need to specify the groups a group admin can impersonate. Do they even match with the groups the user is admin of? Doesn't give the impression. But the group admin will anyway only see the users from the groups he is admin of.

I think it would be way more useful when group admins could just impersonate the users in the groups they are admin of. Why do I need to specify the groups at all? The only use case I can think of would be that I generally want group admins to be able to impersonate their user but I have some group admins that shouldn't be able to. I think this doesn't weigh out the issue that when groups change I always need  to take care of changing the specified groups.

@PVince81 can we schedule the change?

**Comment by PVince81** [comment]
@sharidas can you estimate ?

**Comment by sharidas** [comment]
A rough estimate would be 0.5 md - 0.7 md. @PVince81

**Comment by sharidas** [comment]
Let me know if this proposal looks ok

- Here is a screenshot 
![impersonate](https://user-images.githubusercontent.com/3600427/50687308-c3307a00-1046-11e9-909b-be242ceafc62.gif)

Basically the idea I got is to have 2 options
-  To allow all sub admins to impersonate its group members.
-  To selectively allow sub admins to impersonate group member. 
-  At one point of time, either one option could be availed.

**Comment by sharidas** [comment]
Based on the above proposal https://github.com/owncloud/impersonate/issues/132#issuecomment-451427325 the PR is here https://github.com/owncloud/impersonate/pull/134

**Comment by tomneedham** [comment]
Rather than disabling the other checkbox, it would be better to use a `<input type="radio">` which allows only one toggle. This gives a better UX - otherwise with the proposal above, it is not clear to the user how to get the other checkbox to become enabled again.

**Comment by sharidas** [comment]
> Rather than disabling the other checkbox, it would be better to use a `<input type="radio">` which allows only one toggle. This gives a better UX - otherwise with the proposal above, it is not clear to the user how to get the other checkbox to become enabled again.

Indeed radio button. You are right, it improves the UX. I will implement it with the radio button in the current PR. Thanks.

**Comment by sharidas** [comment]
Updated the UI with radio buttons in the PR https://github.com/owncloud/impersonate/pull/134
One option which I thought would be useful:
- [x] When user selects the radio button to grant all group admins impersonate their user, the drop down list in the second radio button is emptied. Meaning when admin changes the mind and selects the radio button to grant limited group admins access, the group selector is empty. And admin has to start selecting one by one.

**Comment by PVince81** [comment]
@tomneedham this was released with impersonate 0.5.0 now, you may want to notify the customer
