### ISSUE TITLE
Impersonate 0.5.0

### ISSUE THREAD

**Issue by PVince81** [owncloud/impersonate#139]
When taking care of a task (and marking as done), please add your name to the task!

### Reason

- [x] Release needed for [new option for all group admins to impersonate their group members](https://github.com/owncloud/impersonate/pull/134)

### QA

- [x] Create **QA Milestone**
- [x] Move items from `development` to `qa`
- [x] Create release branch with the format "release-$version"
- [x] Create "Impersonate 0.5.0" Testplan @davitol https://github.com/owncloud/impersonate/issues/141

### Documentation

- [ ] Changes in the docs needed?

### Marketing

- [ ] Ping RocketChat channel #marketing
- [ ] Check/adapt info.xml stuff
- [ ] Check/adapt screenshot
- [ ] Blog post or other communication if applicable

### Build

All actions to be done on the release branch from here:
- [x] Bump version in info.xml (no version suffix)
- [x] Update CHANGELOG.md - Change CHANGELOG.md 'Unreleased' to '$version' (final release date unknown)

#### Beta/RC

- [x] Create github tag for 'v${version}RC1' on release branch
- [x] Build and sign RC tarball from github tag 'v${version}RC1' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries: https://github.com/owncloud/impersonate/releases/tag/v0.5.0RC1
- [ ] Test and document in testplan => Final "Go" from QA (set 'QA-ready' label) => else do another RC after fixing issues in the "release-$version" branch

#### Final

- [x] Create github tag for final 'v${version}' on release branch
- [x] Build and sign final tarball from github tag 'v${version}' (see
  handbook for how to build)
- [x] Upload as Github release using changelog entries
- [x] Smoke test tarball (at least install + enable)

### Publishing

- [x] Upload tarball to marketplace (see handbook for details)
- [x] Publish tarball for customers (see handbook for details)
- [x] Send mail to release-coordination with link to this ticket and to the changelog

### Post-release

- [x] Rename QA milestone to '$version'
- [x] Add a new 'Unreleased' section in CHANGELOG.md and add release date '$version - $currentDate' (ex: 3.1.5 - 2018-08-01)
- [x] Create PR to merge changes back to the `master` branch with
  description "Closes #XYZ" with the release ticket number => https://github.com/owncloud/impersonate/pull/143

**Comment by PVince81** [comment]
- [ ] fix makefile https://github.com/owncloud/impersonate/pull/137

@sharidas FYI

**Comment by PVince81** [comment]
RC1: https://github.com/owncloud/impersonate/releases/tag/v0.5.0RC1 @davitol

**Comment by davitol** [comment]
@PVince81 Tarball is QA-ready

**Comment by PVince81** [comment]
final tarball: https://github.com/owncloud/impersonate/releases/download/v0.5.0/impersonate-0.5.0.tar.gz
