### ISSUE TITLE
Missing support for Nextcloud

### ISSUE THREAD

**Issue by TomFernandes** [owncloud/impersonate#15]
Hi,
we use this plugin regularly in ownCloud (8.2). Now, as we intend to migrate to the latest Nextcloud-Release (11.0.2) we notice that this plugin is not compatible out of the box:

```
This app has no minimum Nextcloud version assigned. This will be an error in the future.
This app cannot be installed because the following dependencies are not fulfilled:

    Server version 10 or lower is required.

```
Any plans to support Nextcloud as well?

Thanks for the good work!

**Comment by raykai** [comment]
ya im in need of this to be compatible with Nextcloud too. support would be nice as this is a useful tool.

**Comment by DeepDiver1975** [comment]
This is open source. Pull requests welcome. 
I personally world on owncloud and don't care much about nextcloud-  like visversa

**Comment by butonic** [comment]
As the author of the app I don't plan to invest time to add support for the fork. They don't seem to be interested in a common app api. And I don't have time to maintain compatability for two APIs.

**Comment by hodyroff** [comment]
Thanks for your praises, this is the great work of the ownCloud Team and you do see that there are several reasons to stay with ownCloud or migrate back to ownCloud. Happy to help if you run into any trouble on your way!
ownCloud is here to serve you as a Community or Company!

**Comment by TomFernandes** [comment]
Whoever stumbles upon this thread may be interested that Impersonate is now available for Nextcloud as well: https://apps.nextcloud.com/apps/impersonate
