### ISSUE TITLE
Subadmins do not work

### ISSUE THREAD

**Issue by PVince81** [owncloud/impersonate#18]
See https://github.com/owncloud/impersonate/pull/16#issuecomment-293867566

Need to return the list of groups using a different approach

@sharidas

**Comment by PVince81** [comment]
Simplest idea: add a method on the controller that returns the groups, then read it through ajax

**Comment by sharidas** [comment]
Subadmins do work with the changes we have merged : https://github.com/owncloud/impersonate/pull/24
