### ISSUE TITLE
Move unit tests into tests/unit folder

### ISSUE THREAD

**Issue by phil-davis** [owncloud/impersonate#198]
The unit tests are currently directly inside the `tests` folder. Create `tests/unit` and move the unit tests there.

Related to https://github.com/owncloud/activity/pull/1074 - the logic to decide if a unit test has changed depends on the unit tests being in a directory called `tests/unit`

**Comment by phil-davis** [comment]
Whoever does this, look at other oC10 app repos that have the unit tests in `tests/unit` and do the same.

**Comment by phil-davis** [comment]
@grgprarup FYI I edited my comment https://github.com/owncloud/impersonate/issues/198#issuecomment-1066498570

Please see how much we can make `phunit.xml` (and any other unit test scripts, settings etc) consistent in "every" oC10 app.

**Comment by SagarGi** [comment]
Covered up all the apps having drone star and having phpunit tests. So closing this issue.
