### ISSUE TITLE
Admin must always be able to impersonate anyone

### ISSUE THREAD

**Issue by PVince81** [owncloud/impersonate#20]
Admin must be able to impersonate anyone regardless of group settings.

@sharidas

**Comment by PVince81** [comment]
The controller **must** also validate:

- if admin: always let them
- if subadmin:
    - check if subadmin has access to the user (see an example here https://github.com/owncloud/core/blob/master/settings/Controller/UsersController.php#L499)
    - check if the user is in the whitelisted groups
- if all pass, then go ahead with login switch

**Comment by PVince81** [comment]
- [ ] fix JS side
- [ ] adjust controller validation
- [ ] write unit tests for the controller validation

**Comment by sharidas** [comment]
This issue is resolved with the changes: https://github.com/owncloud/impersonate/pull/24
