### ISSUE TITLE
If Impersonate gets configured, you cant get back to state "unconfigured" (default)

### ISSUE THREAD

**Issue by mmattel** [owncloud/impersonate#210]
Based on a discussion with @jnweiger 

Though this may sound strange, when you install and enable Impersonate but do nothing more, only the ownCloud Admin can impersonate. But when you configure Impersonate to either use group admins for all groups or group admins with defined groups, you never come back to ownCloud admins only. This is because of the radiobuttons in the UI.

Imho a radiobutton is missing to go back to default.

Also see: https://github.com/owncloud/docs-server/issues/633 as there are occ config:app commands (not documented atm), if deleting both app values will reset impersonate to default.

See: https://doc.owncloud.com/server/next/admin_manual/configuration/general_topics/impersonate_users.html#allow-some-or-all-group-administrators-to-impersonate-users

@phil-davis maybe you want to have a look on.

**Comment by phil-davis** [comment]
The workaround is probably that you select "Allow group admins of specific groups to impersonate the users within those groups" and do not put in any groups:
![Screenshot 2022-09-15 at 18-26-45 Settings - ownCloud](https://user-images.githubusercontent.com/1535615/190406561-0450d04b-27c3-4807-ada8-b21c1ec55bb6.png)

And you can "manually" reset the state of all that by:
```
$ php occ config:app:delete impersonate impersonate_all_groupadmins
Config value impersonate_all_groupadmins of app impersonate deleted
$ php occ config:app:delete impersonate impersonate_include_groups
Config value impersonate_include_groups of app impersonate deleted
$ php occ config:app:delete impersonate impersonate_include_groups_list
Config value impersonate_include_groups_list of app impersonate deleted
```

But it would be nice if those buttons could all be turned off. Maybe add a 3rd button "None" that is selected when neither of the other options is wanted?

**Comment by mmattel** [comment]
I propose a third radio button (on top) with:
`Only the ownCloud administrator is allowed to impersonate users.`

**New app variables I had never heard of...**

> And you can "manually" reset the state of all that by:
```
$ php occ config:app:delete impersonate impersonate_all_groupadmins
$ php occ config:app:delete impersonate impersonate_include_groups
$ php occ config:app:delete impersonate impersonate_include_groups_list
```
Looking to the referenced doc-server issue above, only the first var is named, the other two are new. I would then just say list all app config vars of impersonate and delete them all.

**Comment by mmattel** [comment]
Closing via #211
