### ISSUE TITLE
Acceptance tests for impersonate app

### ISSUE THREAD

**Issue by phil-davis** [owncloud/impersonate#215]
It is important to verify both positive and negative features - users should be able to impersonate when the rules allow, but definitely should not be able to impersonate when the rules do not allow it.

Create acceptance tests that verify both positive and negative behaviour.

- default settings - users in the admin group should be able to impersonate other users. sub-admins and ordinary users cannot impersonate anyone
- "Allow all group admins to impersonate users within the groups they are admins of" is set - sub-admins can now impersonate users in the group(s) that they manage
- "Allow group admins of specific groups to impersonate the users within those groups" is set - sub-admins of the specified groups can impersonate users in those groups, but other sub-admins cannot impersonate
- the impersonate app is only enabled for some groups (for the admin group and other group(s)) - an admin can only impersonate users in one of the enabled groups, sub-admins can only impersonate within an enabled group (and one of the other group options is set to allow sub-admins to impersonate)

For positive test scenarios, we can use the UI - an admin or sub-admin can navigate to the Users page, click the Impersonate icon for the user, the impersonations starts, they can log-out and get back to their own account

For negative test scenarios where the admin or sub-admin is restricted, we can also use the UI. The admin or sub-admin can navigate to the Users page and click the Impersonate icon. A message should be displayed to tell them that they cannot impersonate the user. (Or in some cases the Impersonate icon may not even be displayed - sometimes the UI knows exactly which users can be impersonated, and in other cases the UI does not have enough information, so the Impersonate icon is shown but gives an error notification when it is clicked)

We also want some negative test scenarios where an ordinary user "Alice" tries to impersonate another ordinary user "Brian", or a sub-admin tries to impersonate another user who is not in the group that they manage. For those scenarios, the user cannot browse to the Users page, or the Users page will not show the target user. We will need to investigate how the UI actually starts impersonation (what API requests does it send), and then attempt those API requests in the test. The requests should get some 4xx forbidden or not found response.

**Comment by phil-davis** [comment]
This screenshot shows the 3 radio-button settings available in Admin Settings, User Authentication
https://user-images.githubusercontent.com/1535615/190411965-5da83083-989b-4780-9f01-b1b77300799e.png

**Comment by SwikritiT** [comment]
The api tests have been added in 
- https://github.com/owncloud/impersonate/pull/217

TODO:
- [ ] add UI tests

**Comment by SwikritiT** [comment]
Both the PR for API and UI tests addition are merged. So closing this as done
