### ISSUE TITLE
Return to first user in case of multiple step impersonate

### ISSUE THREAD

**Issue by PVince81** [owncloud/impersonate#22]
### Steps

1. Login as admin "admin1"
1. Impersonate another admin "admin2"
1. Impersonate another user "user3"
1. Log out

### Expected
Logs out back to "admin1"

### Actual
Logs out to "admin2".

@pmaier1 @butonic let me know if you think otherwise

**Comment by pmaier1** [comment]
Hmm, to really be consistent you should be impersonated as "admin2" when logging out as "user3" and the following logout would get you back to "admin1". Another interpretation would be to say 'when you log out you quit impersonation'. Then your approach would be the way to go.

The only use case I can imagine right now is that "groupadmin1" needs to impersonate users that are in another group and therefore first impersonates "groupadmin2" to reach e.g. "user3". Then it would make sense for me to be "groupadmin2" again after logging out.

Not even sure if (group)admins should be able to impersonate other (group)admins at all. 
If the answer to this question is 'yes' (@hodyroff ; I would say no) then I think better UX would be logout = quit impersonation => log out back to "admin1" as suggested.

**Comment by PVince81** [comment]
> Hmm, to really be consistent you should be impersonated as "admin2" when logging out as "user3" and the following logout would get you back to "admin1"

This would require keeping a stack of previous users in the session. Technically possible but doesn't feel right. Also you could as "admin1" impersonate "admin2" then impersonate "admin1" again to go back and forth...

**Comment by pmaier1** [comment]
> This would require keeping a stack of previous users in the session. Technically possible but doesn't feel right. Also you could as "admin1" impersonate "admin2" then impersonate "admin1" again to go back and forth...

Yes ok, almost thought so. Then your solution is the right way: logout = quit impersonation => log out back to "admin1" as suggested

**Comment by pmaier1** [comment]
For now we allow impersonating all other users, v2 should then make it configurable https://github.com/owncloud/impersonate/issues/23.

**Comment by PVince81** [comment]
"all other users" based on the whitelist group list from which users can be impersonated ?

**Comment by pmaier1** [comment]
> "all other users" based on the whitelist group list from which users can be impersonated ?

I actually thought to enable impersonation of _all_ users (regular, admin, group admin). What do you mean?

**Comment by PVince81** [comment]
There is a setting in the admin page where you can select groups for which the users within these groups can be impersonated. See https://github.com/owncloud/enterprise/issues/1876 which leads to

![impersonate-setting](https://cloud.githubusercontent.com/assets/277525/23859784/2694f338-0805-11e7-8247-75132e49fc77.png)

Let me know whether there's a misunderstanding...

**Comment by pmaier1** [comment]
Ah ok - just a misunderstanding on my side. In the end this means that we already have some restriction to prevent impersonating admins of other groups - nice!

**Comment by sharidas** [comment]
This is accomplished with the changes we got merged: https://github.com/owncloud/impersonate/pull/24
