### ISSUE TITLE
Web ui tests are failing in nightly

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/impersonate#230]
Build link: https://drone.owncloud.com/owncloud/impersonate/1984/11/13

tests are failing in step 

```
Failed step: Then the administrator should be redirected to the files page of user "Alice"
        Page\OwncloudPage::waitTillXpathIsVisible xpath: //span[contains(@id,"expandDisplayName") and text()="Alice"] cannot find element (SensioLabs\Behat\PageObjectExtension\PageObject\Exception\ElementNotFoundException)
```

Seems like some selector got changed

**Comment by SwikritiT** [comment]
@phil-davis just to let you know this issue might not be related to symphony

**Comment by phil-davis** [comment]
yes, I will check. The UI behavior change could happen if some underlying API requst is now failing.
