### ISSUE TITLE
Release makefile

### ISSUE THREAD

**Issue by PVince81** [owncloud/impersonate#25]
Create a Makefile that builds a release tarball, stripped of all unwanted files.

Also need a way to be able to sign it.

Some example Makefile here: https://github.com/owncloud/market/blob/master/Makefile (the npm bits are not needed).
For signing use this command: https://github.com/owncloud/customgroups/blob/master/rules/sign.mk#L4 (and see https://doc.owncloud.org/server/10.0/developer_manual/app/code_signing.html#how-to-get-your-app-signed)

@sharidas

**Comment by sharidas** [comment]
Created a makefile. https://gist.github.com/sharidas/27b649c25dd61b7348e2868bcf5a3308 signing part is pending. I will update the same.

**Comment by DeepDiver1975** [comment]
looks here - has signing in the make file https://github.com/owncloud/contacts/blob/master/Makefile

**Comment by PVince81** [comment]
is this done ? close ?

**Comment by PVince81** [comment]
@sharidas ^

**Comment by sharidas** [comment]
This is completed. https://github.com/owncloud/impersonate/blob/master/Makefile

**Comment by sharidas** [comment]
Marking this task as closed.
