### ISSUE TITLE
QA

### ISSUE THREAD

**Issue by PVince81** [owncloud/impersonate#29]
Prerequisite before publishing to market

@owncloud/qa @butonic @sharidas 

@sharidas can you write a test plan below based on your experience with the app ?

**Comment by sharidas** [comment]
Scope of testing:
1) If the app is just enabled. Then it will behave as previous version with the following exceptions:
    a) Users can be impersonated only if they are logged in once.
    b) Except the logged in users other users can be impersonated. ( this is valid throughout the app )
2) If the app is enabled and certain subadmin are whitelisted under settings->Additional->Impersonate Settings:
     a) Any subadmin user who is not whitelisted when logged in cannot impersonate users under it.
         The impersonate icon will not be visible for them.
     b) Any subadmin user who is whitelisted when logged in can impersonate users under it. If the users have logged in a tleast once.
     c) Admin user can impersonate any users. This is the only exceptional user.
3) If the app is enabled and a user who doesn't belongs to the group, who is a subadmin of the group when logged in can impersonate all the users under it, if that group is whitelisted. For example if  there are 2 groups : group1 and group2. And user1, user2, user3 belong to group1. user1 is the subadmin of group1.  user3 subadmin of group2. user4, user5, user6 belong to group2. Then if user3 is logged in. user3 can impersonate all the users: user4, user5 and user6.

So far we saw addition of subadmin groups to the whitelist. Now lets see removal of the groups:
1) If the app is enabled and subadmin group, group2, from the step3 is removed. Login as user3. Now user3 cannot see impersonate icon associated with user4, user5 and user6.
2) The current/loggedin user will cannot impersonate itself. This is applicable to admin/subadmin user. 
3) If logged in as admin user and group1 is added to whitelist. Then try to impersonate user1, which is a subadmin of group1. Then user lands up in the home page of user1. Try to impersonate user2. User reaches home page of user2. Try to logout. The user should be back to admin home page. The higlight here is: after impersonate operation if tried to logout, the user reaches the home page of the first user who tried to impersonate.

Out of scope:
1) There is no command line utility for this app. User can enable the app just like any other app using occ command.
