### ISSUE TITLE
Add "impersonate" action to the user list instead of the admin settings

### ISSUE THREAD

**Issue by butonic** [owncloud/impersonate#3]
OC8.2 will allow searching in the user list. We should just add an "impersonate" action next to the delete action. Then again @jancborchard might have a better idea where to place this action in the UI.

**Comment by BOGitHub7** [comment]
User searching is available in OC 8 now.  I was also trying to implement something similar but haven't had a chance to start on it yet.

**Comment by butonic** [comment]
ifixed by https://github.com/owncloud/impersonate/commit/d6f3dcf9377848960b08d5efe4ed6a1e33ab60e3
