### ISSUE TITLE
Move to new info.xml registered settings panels

### ISSUE THREAD

**Issue by tomneedham** [owncloud/impersonate#38]

**Comment by SergioBertolinSG** [comment]
Currently impersonate is on additional settings. It requires a special icon and a particular panel.

cc @felixheidecke for the icon.

**Comment by felixboehm** [comment]
@pmaier1 can you review and fix the info.xml, please

**Comment by tomneedham** [comment]
This needs some code moving around, and then registering a class in the info xml - 10 min job if its urgent?

**Comment by tomneedham** [comment]
>It requires a special icon and a particular panel.

Does it really need its whole own section?

**Comment by tomneedham** [comment]
stick it under 'user authentication' IMO

**Comment by pmaier1** [comment]
> @pmaier1 can you review and fix the info.xml, please

I will take care tomorrow but this ticket is about the categorization in the admin settings. I don't think that it needs an own section. Agree with @tomneedham that the "User Authentication" section fits best. Can you take care?

**Comment by pmaier1** [comment]
According to https://github.com/owncloud/impersonate/pull/54#issuecomment-334695925 we should move this to the development milestone and release a version without changing settings panels first, right?

**Comment by DeepDiver1975** [comment]
> According to #54 (comment) we should move this to the development milestone and release a version without changing settings panels first, right?

yes

**Comment by felixheidecke** [comment]
Is this icon too suspicious? http://fontawesome.io/icon/user-secret/

**Comment by SergioBertolinSG** [comment]
I agree with @tomneedham about putting impersonate in the user authentication section, no icon needed in this case.

**Comment by pmaier1** [comment]
Thanks, but no icon needed. Moving to the version after the current one.

**Comment by PVince81** [comment]
https://github.com/owncloud/impersonate/pull/54
