### ISSUE TITLE
[OC 9.0] Cannot see Impersonate icon

### ISSUE THREAD

**Issue by dnviti** [owncloud/impersonate#47]
Owncloud Version 9.0.10
I installed the app like any other, put it in the apps folder, activated experimental apps, enabled the app... but i cannot see the impersonation icon, have i done something wrong?

**Comment by PVince81** [comment]
Hmm I don't think this app is compatible with 9.0 as it might require stuff only available in OC 10.

I do see that info.xml states that min-version is 9.0.

@sharidas @butonic ?

**Comment by dnviti** [comment]
Is there a way to make it work with 9.0?...
At IT Dept we need this functionality for security and OC v10.0 is not quite stable enough for production porpuses.

**Comment by dnviti** [comment]
UP My problem is still there!

**Comment by dnviti** [comment]
@PVince81 Can you help me, please?

**Comment by sharidas** [comment]
@dnviti If it is not problematic, can you please upgrade the system to 10.0.0? A humble request.

**Comment by michaelstingl** [comment]
@dnviti oC 9.0.x is EOL soon. In it's last month, it will get security fixes only. (see [Maintenance and Release Schedule](https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule))

Please help test the [10.0.3 beta](https://owncloud.org/install/#testing-development) and provide feedback, so ownCloud developers can release the best and most stable 10.0.3 possible. This should be the fastest fix for your issue.

**Comment by felixboehm** [comment]
10.0.3 is production ready. Give it a try.

**Comment by dnviti** [comment]
I cannot "test" i work for a 500+ employees company, if i encounter e blocking bug the company will not be able to use the cloud for a bunch of hours/days, this cannot happen.
If 10.0.3 is stable for production i'll give it a try, we will see.
