### ISSUE TITLE
Provide signature.json

### ISSUE THREAD

**Issue by develth** [owncloud/impersonate#52]
Would be nice to get this app signed, the message is annoying :)

Thanks & Cheers

**Comment by DeepDiver1975** [comment]
Where do you see any message regarding signature.json?

If you grab the app from the marketplace (easiest is to open up the market app in your owncloud instance) you will get version 0.1.0 which holds the signature.json file - https://marketplace.owncloud.com/apps/impersonate

**Comment by develth** [comment]
Ok - installed it from github source...

Thanks!
