### ISSUE TITLE
Testing impersonate version 0.1.1

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/impersonate#56]
## Impersonate Test Plan

| Test Case                                | Expected Result                          | Result         | Related Comment |
| ---------------------------------------- | ---------------------------------------- | -------------- | --------------- |
| Enable the app.                          | No problems found.                       | ✅   | Missing dist target https://github.com/owncloud/impersonate/issues/57  - Fixed              |
| As admin create a group 'group1' add three members 'user1', 'user2', 'user3'. Make 'user1' group admin of 'group1'. Login as 'user1', go to the users view. Impersonate 'user2'. | 'user1' can impersonate 'user2'. See his files. Behave like him. Like if he were logged in. | ✅              |                 |
| Check that a user who is not group admin cannot impersonate anyone. |                                          | ✅             |                 |
| As admin create a group 'group1' add four members 'user1', 'user2', 'user3' and 'admin' being admin user of the server. Make 'user1' group admin of 'group1'. Login as 'user1', go to the users view. Impersonate 'admin'. | Super admin cannot be impersonated.      | ✅             |                 |
| When impersonating a user, a warning appears adverting that you have logged as another user. | a warning appears and disappears after a while. Edit: No need to disappear. | ✅              |  https://github.com/owncloud/impersonate/issues/59  Works as expected.             |
| Check that impersonate options appears in the correct settings panel. |                                          | ❌             |   :  https://github.com/owncloud/impersonate/issues/38             |
| **Interaction with other Apps**          |                                          |                |                 |
| Having ldap set up, enable impersonation for an ldap group. Make a user group admin. Using that user impersonate one of the other members of the ldap group. | Users can be impersonated without problems. | ❌             |   https://github.com/owncloud/impersonate/issues/66              |
| A guest user cannot impersonate other users. |                                          | ✅             |  This works just because impersonate app is not whitelisted to guests app               |
| A guest user cannot be impersonated / can logout | | :x: | Impersonated guest cannot logout https://github.com/owncloud/impersonate/issues/64   |
| **Browsers**                             |                                          |                |                 |
| Check that all the UI elements are usable when browsing with safari. |                                          | ✅  |                 |
| Check that all the UI elements are usable when browsing with chrome. |                                          | ✅  |                 |
| Check that all the UI elements are usable when browsing with firefox. |                                          | ✅  |                 |
| Check that all the UI elements are usable when browsing with edge. |                                          | ✅  |                 |
| Check that all the UI elements are usable when browsing with IE11. |                                          | ✅  |                 |

**Comment by patrickjahns** [comment]
@SergioBertolinSG 
please close or move accordingly - 0.1.1 has been released
