### ISSUE TITLE
After a failed impersonation the user impersonates himself.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/impersonate#58]
### Steps to reproduce

0. Having a group enabled for impersonation called 'group1' including as members an admin or a user who didn't login yet. Also add a group admin called 'group_admin'.
1. As 'group_admin', go to users and try to impersonate an admin or a user who didn't login yet.
2. Close the error dialog saying that you cannot impersonate.
3. As a group admin go to a different page, for example settings or files.

### Expected behaviour
Nothing, the user keeps logged in and nothing particular happens.

### Actual behaviour
The 'group_admin' user impersonates himself.

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
current Master
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.3.0","versionstring":"10.0.3 beta","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No.

**Logs**
```
```

### Client configuration

**Browser**
Firefox

cc @sharidas

**Comment by pmaier1** [comment]
So, impersonating a user with higher privileges should be prevented. This is the case as I understand it. Issue here is that a second session is opened for the same user, right? Logging out would cause to be logged in with the first session again, right?

**Comment by sharidas** [comment]
PR for this bug is here: https://github.com/owncloud/impersonate/pull/62

**Comment by SergioBertolinSG** [comment]
> Issue here is that a second session is opened for the same user, right? Logging out would cause to be logged in with the first session again, right?

yes.

In this case not higher privileges, just the same as it is the same user logged again.
