### ISSUE TITLE
Warning message showing that we have impersonated a user never disappear.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/impersonate#59]
### Steps to reproduce

0. Having a group enabled for impersonation called 'group1' having as member 'user1', add a group admin called 'group_admin'.
1. As 'group_admin', go to users and impersonate 'user1'.
2. Go to files view and wait some minutes.

### Expected behaviour
The yellow warning disappears after a while.

### Actual behaviour
yellow warning never disappears.

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0

**ownCloud version:** (see ownCloud admin page)
current Master
{"installed":"true","maintenance":"false","needsDbUpgrade":"false","version":"10.0.3.0","versionstring":"10.0.3 beta","edition":"Community","productname":"ownCloud"}

**Updated from an older ownCloud or fresh install:**
Fresh

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** 
No.

**Logs**
```
```

### Client configuration

**Browser**
Firefox, Chrome

cc @sharidas

**Comment by SergioBertolinSG** [comment]
@pmaier1 it only disappears when we log out. It this expected or a bug?

**Comment by pmaier1** [comment]
> @pmaier1 it only disappears when we log out. It this expected or a bug?

Yes, of course. The message is is needed to constantly remind the user that he's logged in as another user. So for the whole time of impersonation we need the message visible. Closing. Please reopen if I misunderstood something.
