### ISSUE TITLE
Regression caused due to new logout change in the app in 10.0.3

### ISSUE THREAD

**Issue by sharidas** [owncloud/impersonate#69]
This issue is to point out the fact that with the latest change made https://github.com/owncloud/impersonate/pull/68 would cause a regression with core version 10.0.3. Let me explain why it causes.
We have removed the logout logic from the frontend (js) and made it work with the backend php. And hence we made change in the core's logout logic to trigger a symfony event. This event will be listened by the impersonate app. Which then takes the logic to the logoutcontroller. And hence the logoutcontroller would do the action and will decide to cancel the logout from the core's logout logic. 

In 10.0.3 the the core doesn't have the change to trigger the event. So the app's logout controller wouldn't be called and hence the user will be logged out and a login page would be seen. Instead user should see the user who impersonated the current user. This won't happen with 10.0.4. As the core has the change to take care. So it becomes a regression.

**Comment by PVince81** [comment]
But we haven't merged https://github.com/owncloud/impersonate/pull/68 so no regression exists at this point ?

**Comment by SergioBertolinSG** [comment]
Ah I was confused sorry. I thought this was happening with current master.

So I suggest to release impersonate as it is now (without #68) and merge it after releasing it for the next version (0.1.2 maybe?) .

**Comment by sharidas** [comment]
Ok. So I will close this issue.
