### ISSUE TITLE
Cannot impersonate with stable10 and verifyAuthHeaders change

### ISSUE THREAD

**Issue by PVince81** [owncloud/impersonate#74]
### Steps

1. Check out core stable10, any commit after https://github.com/owncloud/core/pull/28733
1. Try impersonating a user

### Expected
Impersonation works.

### Actual
Logout is called.

### Version
Core: stable10 (before v10.0.4RC1), impersonate app "release" branch (version 0.1.0)

What @sharidas and I observed was that the introduction of verifyAuthHeaders in core in https://github.com/owncloud/core/pull/28733 has introduced the problem.

It looks like the token auth module has a mapping between session id and the user id in the DB table oc.auth_tokens. Maybe it's used for revoking sessions or something.

During impersonation, the session id is not reset, so the mapping stays.

Possible solutions to look into:

1) Clear the session in way that resets the session id, maybe logout admin first ?
or
2) Provide a method `switchUser()` in core that properly cleans up everything needed, including the token manager stuff. The impersonate app is not supposed to be aware of this token manager or any third party auth plugins.

I suspect that the best solution is still making sure the session id changes because we cannot guarantee whether there are any third party auth solutions that also use the session id.

**Comment by PVince81** [comment]
Note that I don't think we can revert the core change as it's necessary for other things (clients) and for auth consistency. So we need to find a solution specific to the impersonate app.

At this stage it is not clear yet whether the solution will require core changes/additions.

cc @DeepDiver1975

**Comment by patrickjahns** [comment]
Is this fixed by #80?

**Comment by sharidas** [comment]
This is fixed by https://github.com/owncloud/impersonate/pull/80
