### ISSUE TITLE
ownCloud 9 compatibility?

### ISSUE THREAD

**Issue by koenlek** [owncloud/impersonate#8]
Are you planning to add owncloud 9 compatibility? If so, any estimate when more or less? I really miss this feature now already... I am currently running latest master, and it seems to work, but when I click the impersonate button, it just takes me to my personal Files overview, rather than the one from that person...

**Comment by TomFernandes** [comment]
I am also missing this feature in OC9.

**Comment by m4lvin** [comment]
It works in OC9 with this small fix: https://github.com/m4lvin/impersonate/commit/36a7f9ca23f1fac62c889cb57db9a354e4152ed0

**Comment by mmattel** [comment]
@m4lvin  Can you do a PR so it can become reviewable respectively mergable?

**Comment by mdmamde** [comment]
ownCloud 9.0.2 (stable) 
also with implemented fixes
standard login- functionality.

impersonate isnt working for me...

**Comment by mdmamde** [comment]
1.)sorry figured out to click on the user icon/symbol in the user-list for impersonate
2.)when impersonating i get an error: Internal Server Error blabla lock into log files...blabla
Technical details
Remote Address: ****.***.****.*** (some ip adress here)
Request ID: V4u6NVUNltcAAGBD4zEAAAAE

then i click browser-back-button->impersanoted ok!

**Comment by mdmamde** [comment]
log:

Error	PHP	rmdir(owncloud directory/tmp//oc_tmp_utndJX-folder): Directory not empty at /path to owncloud/lib/private/helper.php#231

Error	PHP	rmdir(owncloud directory/tmp/oc_tmp_utndJX-folder/news): Directory not empty at /path to owncloud/private/helper.php#225	

Error	PHP	rmdir(owncloud directory/tmp/oc_tmp_utndJX-folder/news/vendor): Directory not empty at /path to owncloud/lib/private/helper.php#225

**Comment by mmattel** [comment]
@mdmamde please report issues in the created PR #9 and not here. That´s what the PR is for. Else we lose tracking and progress for changes made.
