### ISSUE TITLE
0.1.2 

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/impersonate#86]
## Reason
Impersonate app will break with 10.0.4 Release - fix is in https://github.com/owncloud/impersonate/pull/80

## QA
- [x] Create release branch https://github.com/owncloud/impersonate/tree/release/0.1.2
- [x] Test scenarios - done by @sharidas 

| Scenario  | Second Header |
| ------------- | ------------- |
| 1. Regular oC users impersonate and logout | ✅  |
| 2. Guest users impersonate | ✅  |
| 3. LDAP users can be impersonated and logged out back. | ✅  |
| 4. Nested impersonation - wont be allowed  | ✅  |
| 5. Cannot impersonate users who never logged in  | ✅  |
| 6. Group admins who are whitelisted can impersonate their users else cannot | ✅  |
| 7. Admin users can impersonate any users   |  ✅  |

## Build & Marketplace release

- [x] Bump version in info.xml https://github.com/owncloud/impersonate/pull/90
- [x] Update CHANGELOG.md https://github.com/owncloud/impersonate/pull/90
- [x] Create github tag for '$version' https://github.com/owncloud/impersonate/releases/tag/v0.1.2
- [x] Build and sign tarball from github tag '$version'
- [x] Upload to marketplace
- [x] Rename QA milestone to '$version'
- [x] Change CHANGELOG.md 'Unreleased' to '$version' and add a new 'Unreleased' section
- [x] Create PR to merge changes back to `master` https://github.com/owncloud/impersonate/pull/92

cc @pmaier1 @sharidas 
Changes: https://github.com/owncloud/impersonate/compare/v0.1.1...master

**Comment by sharidas** [comment]
I would also like to include the commit https://github.com/owncloud/impersonate/pull/68. Since core 10.0.4 is released, I would like to have this too in 0.1.2 release of the impersonate app. Hope we have QA time to test this too?

**Comment by patrickjahns** [comment]
@sharidas 
Everything that is in master, will currently be scheduled for the release, can you clean up the [QA Milestone](https://github.com/owncloud/impersonate/milestone/5) and push task to `development` or `backlog` 

I will create the releae branch later today

**Comment by sharidas** [comment]
Testing impersonate for 0.1.2:
1. Test impersonation of regular oC users with admin
2. Check if whitelisting of group admins help impersonating the users of the group
3. Guest users should be able to impersonate and logout back to the orignal user who impersonated them.
4. LDAP users should also be able to impersonate.

**Comment by patrickjahns** [comment]
Released on marketplace 🎆 🚀
