### ISSUE TITLE
Impersonate logs out after owncloud upgrade to 10.0.7.2

### ISSUE THREAD

**Issue by fretscha** [owncloud/impersonate#96]
Impersonate logs out after upgrade to 10.0.7.2

Docker Version

version | 10.0.7.2
versionstring | 10.0.7
edition | Community

/apps/impersonate/user
/apps/files
response Headers
Set-Cookie:oc_username=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; secure; HttpOnly
Set-Cookie:oc_token=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; secure; HttpOnly
Set-Cookie:och4chaiop7i=dnnu9lr5vlk64va4kvihlr7vn4; path=/; secure; HttpOnly
Set-Cookie:oc_remember_login=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; secure; HttpOnly
Set-Cookie:oc_username=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; secure; HttpOnly
Set-Cookie:oc_token=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/; secure; HttpOnly
Set-Cookie:oc_remember_login=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; secure; HttpOnly

**Comment by sharidas** [comment]
Based on my investigation with core version 10.0.6 and impersonate app version 0.1.2 version ( on a scratch installation ):
- [x] admin user is able to impersonate other users
When impersonate app is configured to whitelist groups. The subadmin of the group can impersonate users belonging to the group ( note: the user should be logged in first ).
- [x] Verified that logout is working properly

**Comment by sharidas** [comment]
With 10.0.7 version here is the gif captured from my local machine:
![impersonate_10_0_7](https://user-images.githubusercontent.com/3600427/36724489-5be38bc4-1bd9-11e8-842a-35575b4528fa.gif)

**Comment by sharidas** [comment]
@fretscha Can you help me by sharing the screenshot if possible?

**Comment by fretscha** [comment]
@sharidas many thanks for your help. "occ market:upgrade" did not work as expected and the impersonate app was still on version 1.1 after a explicit upgrade to 1.2,  impersonate is working like a charm.

Problem resolved. You can close the issue.

**Comment by sharidas** [comment]
@fretscha Thanks for verifying. Happy hacking.
